"""Shared BCP-47 locale mappings for Vexyl-STT and Vexyl-TTS."""

# ISO 639-1/3 codes and full language names → Vexyl BCP-47 locale tags.
# "auto" passes through unchanged for STT language-detection mode.
ISO_TO_BCP47: dict[str, str] = {
    # Short ISO codes
    "en":  "en-IN",
    "hi":  "hi-IN",
    "kok": "kok-IN",
    "kn":  "kn-IN",
    "doi": "doi-IN",
    "brx": "brx-IN",
    "ur":  "ur-IN",
    "ta":  "ta-IN",
    "ks":  "ks-IN",
    "as":  "as-IN",
    "bn":  "bn-IN",
    "mr":  "mr-IN",
    "sd":  "sd-IN",
    "mai": "mai-IN",
    "pa":  "pa-IN",
    "ml":  "ml-IN",
    "mni": "mni-IN",
    "te":  "te-IN",
    "sa":  "sa-IN",
    "ne":  "ne-IN",
    "sat": "sat-IN",
    "gu":  "gu-IN",
    "or":  "or-IN",
    "auto": "auto",
    # Full language names (lowercase)
    "english":   "en-IN",
    "hindi":     "hi-IN",
    "malayalam": "ml-IN",
    "tamil":     "ta-IN",
    "telugu":    "te-IN",
    "kannada":   "kn-IN",
    "bengali":   "bn-IN",
    "gujarati":  "gu-IN",
    "marathi":   "mr-IN",
    "punjabi":   "pa-IN",
    "odia":      "or-IN",
    "assamese":  "as-IN",
    "urdu":      "ur-IN",
    "nepali":    "ne-IN",
    "sanskrit":  "sa-IN",
    "konkani":   "kok-IN",
    "bodo":      "brx-IN",
    "dogri":     "doi-IN",
    "maithili":  "mai-IN",
    "manipuri":  "mni-IN",
    "santali":   "sat-IN",
    "sindhi":    "sd-IN",
    "kashmiri":  "ks-IN",
}
